### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by zhenya46** [danrom11/No-fingerprint#1]
Как получить код активации  No fingerprint?

**Comment by danrom11** [comment]
Если вы хотите получить ключ на No fingerprint, то его нужно приобрести.
Есть несколько способов приобрести ключ на платную версию, это через сайт https://kwork.ru/software/4950481/anonimniy-brauzer-fingerprint-botov-i-torgovykh-ploshchadok или же на прямую со мной

**Comment by zhenya46** [comment]
Добрый день, я отправил вам деньги вот с этой почты, но в ответ тишина zhenyaSap@yandex.ru  24.04.2020, 21:56, "danrom11" <notifications@github.com>: Если вы хотите получить ключ на No fingerprint, то его нужно приобрести.Есть несколько способов приобрести ключ на платную версию, это через сайт https://kwork.ru/software/4950481/anonimniy-brauzer-fingerprint-botov-i-torgovykh-ploshchadok или же на прямую со мной—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by danrom11** [comment]
Извините, сейчас же отправим!

**Comment by zhenya46** [comment]
Ключ получил, скажите что это выскакивае при активации  24.04.2020, 23:13, "Daniil" <notifications@github.com>: Извините, сейчас же отправим!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by danrom11** [comment]
Что выскакивает ?

**Comment by zhenya46** [comment]
24.04.2020, 23:30, "Daniil" <notifications@github.com>: Что выскакивает ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by danrom11** [comment]
Я не вижу что вы присылаете

**Comment by zhenya46** [comment]
Я скриншот присылаю, при активации ошибка  24.04.2020, 23:34, "Daniil" <notifications@github.com>: Я не вижу что вы присылаете—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by danrom11** [comment]
Отправьте скриншот на почту danrom11@bk.ru

**Comment by danrom11** [comment]
Вы какую версию программы скачали ?

**Comment by zhenya46** [comment]
Последняя 4.224.04.2020, 23:58, "Daniil" <notifications@github.com>:
Вы какую версию программы скачали ?

**Comment by danrom11** [comment]
решение проблемы -> зайдите в корневую папку программы и найдите текстовый документ "key.txt"

**Comment by danrom11** [comment]
если он у вас есть

**Comment by zhenya46** [comment]
Что то я его там не вижу24.04.2020, 23:59, "Daniil" <notifications@github.com>:
если он у вас есть

**Comment by danrom11** [comment]
почему то он у вас не создался, возможно проблема с серверам. Создайте сами его, обязательно должно быть имя "key" в формате .txt

**Comment by danrom11** [comment]
Стойте, можете не создавать! Нужно запустить приложение от имени администратора, так как у вас оно установлено на диск "C" в программных файлах!
А для этого нужны права! Запустите просто приложение от Имени Администратора

**Comment by zhenya46** [comment]
От имени администрации нету, только просто открыть (Скрин) Мож попробовать переустановить на диск Е  25.04.2020, 00:07, "Daniil" <notifications@github.com>: Стойте, можете не создавать! Нужно запустить приложение от имени администратора, так как у вас оно установлено на диск "C" в программных файлах!А для этого нужны права! Запустите просто приложение от Имени Администратора—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by danrom11** [comment]
Да можете переустановить на другой диск, вскоре эту проблему поправим!

**Comment by zhenya46** [comment]
Переустановил, теперь всё нормально, скажите отпечаток меняет при новом запуске?25.04.2020, 00:15, "Daniil" <notifications@github.com>:
Да можете переустановить на другой диск, вскоре эту проблему поправим!

**Comment by danrom11** [comment]
Да меняет если вы не вписываете свой в поле fingerprint, если его оставить пустым то он будет всегда разный генерировать, а если писать туда свой, то он будет его применять

**Comment by zhenya46** [comment]
Спасибо! Если буду использовать с VPN, распознать не смогут?25.04.2020, 00:45, "Daniil" <notifications@github.com>:
Да меняет если вы не вписываете свой в поле fingerprint, если его оставить пустым то он будет всегда разный генерировать, а если писать туда свой, то он будет его применять

**Comment by danrom11** [comment]
Да не могут, даже Cavans

**Comment by danrom11** [comment]
Вы можете так же использовать встроенный прокси
